# ch. 11 Numpy

-> 배열데이터(array): 여러 데이터를 담는 것을 배열이라고 한다.  
일반적으로 다른 랭기지에서는 배열은 ( 1, 2, 3   ) 이런 식으로 쓴다.  
파이썬에서는 특이하게 리스트와 배열 튜플 등을 구분한다.  

파이썬 내장:  
    리스트(list): [ 1,2, 3 ]  
    튜플(tuple): ( 1, 2, 3 )  
    셋(set): { 1, 2, 3 }  
    딕트(dict): {"id": 'kim', 'pw' : 111}  
파이썬에 내장된 형태들: list, tuple, set, dict, int, str, bool, date, datetime.  


-> 위의 데이터 형식을 배열화  
배열: [ 1 2 3 ]******** -> 파이썬에 정식으로있는 문법은 아님.(사용자가 직접 작성하는 건 아니다.)  
                           -> Numpy.py 패키지에서 해준다.(원래 따로 설치했어야됐는데 파이썬 안으로 들어왔다.)  
배열의 파일 형식은 numpy  

-> 파이썬 내장만으로는 여러 개 데이터 한 번에 다루기 어렵다.(한 개 씩 해야돼서 속도가 안 남) 이걸 가능하게 해주는 게 numpy  
-> 근데 numpy 다루기 어렵다.  
-> numpy를 다루기 쉽게 해주는 게 데이터프레임!  

class DataFrame(numpy): DataFrame은 numpy를 부모의부모의...부모클래스로 하는 클래스  
데이터프레임 == 테이블형태  
데이터프레임 형태 예시:  
empno ename  
*------* *-------*  
7788  smith  
8892  allen  

데이터프레임은 numpy보다 추가된 기능도 있고 overriding한 것도 있어서 numpy를 써야될 때도 있다. -> 둘 다 필요.  
  
### 배열은 numpy, 데이터프레임은 pandas 설치 필요
      

In [2]:
# numpy
import numpy as np # 100% np로 alias 준다.
arr= np.array( [1,2,3]) # np.array( ) 캐스팅해준다.
print(arr, type(arr)) # 타입: numpy.ndarray : numpy의 numpy data의 array 타입이다.


[1 2 3] <class 'numpy.ndarray'>


# 11장 데이터 분석을 위한 패키지

### 배열의 연산

#### 기본 연산

**[11장: 225페이지]**

In [4]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

**[11장: 226페이지]**

In [5]:
arr1 + arr2 # array끼리는 덧셈도 가능하다.
            # 리스트형처럼 결과 나오지만 print 하면 array 꼴로 나온다.
            # 리스트에서 덧셈 하면 붙여졌다.
            # item에 대한 핸들링이 list(껍데기 채)
            # 값에 대한 핸들링이 arry(세부적인 값)
            # 값의 개수가 같아야 합산 가능.

array([11, 22, 33, 44])

**[11장: 226페이지]**

In [6]:
arr1 - arr2 # 각 값들을 빼줘
            # 리스트는 뺄셈 안 됨.

array([ 9, 18, 27, 36])

In [17]:
# [10, 20, 30, 40] - [1, 2, 3, 4] 불가
list=[10, 20, 30, 40]
del list[3]             # -------------delete
print(list)
list.append(50)         # -------------insert
print(list)
print(list[1])          # -------------select
print(list[1:4])        # ------------- 뒤에 거 미만임에 유의!!!
list[0]=70              # update
print(list)

[10, 20, 30]
[10, 20, 30, 50]
20
[20, 30, 50]
[70, 20, 30, 50]


**[11장: 226페이지]**

In [18]:
arr2 * 2 # 개별 값 더블
        # 리스트는 두 번 반복

array([2, 4, 6, 8])

미니 미션
* list 값을 두 배 하시오

In [31]:
# [70,20,30,50] -> 리스트를 array 연산처럼 더블해보자
# for문 쓰지 말고 array 쓰라고 알려준 거다~~~

list=[70,20,30,50]
for i in range(len(list)):
    list[i]=list[i]*2
    
res=list
print(res)

res=list

list2=[70,20,30,50]
for i, x in enumerate(list2):
    list2[i]=x*2
    
res2=list2

print(res)
print(res2)

####가장 손 쉬운 방법
list3=[70,20,30,50]
res3= np.array(list3)*2
print(res3)

[140, 40, 60, 100]
[140, 40, 60, 100]
[140, 40, 60, 100]
[140  40  60 100]


**[11장: 226페이지]**

In [33]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [34]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [35]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [36]:
arr1 / arr2 # array/array 하면 float이 된다.

array([10., 10., 10., 10.])

In [37]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

arr1 > 20 값을 출력
출력 결과: 30, 40

In [63]:
arr1 = np.array([10, 20, 30, 40])
arr1 > 20 # 일괄 값처리 가능.

array([False, False,  True,  True])

In [67]:
arr1 = np.array([10, 20, 30, 40])
for a in arr1:
    if a>20:
        print(a)

## 아래와 같은 방법으로도 가능.(강사님 코드 참고)

temp=arr1>20
print(temp)
        
for i, t in enumerate(arr1>20):
    if t==True:
        print(arr1[i])

30
40
[False False  True  True]
30
40


In [ ]:
int(True), int(False) # 1, 0

bool(1), bool(0) # True, False

## 반드시 암기

* <font color=red> list --> arr : np.array(list)</font>
* <font color=red> arr --> list : list(arr) XX (이건 내장형식에서 내장형식으로!!), arrary이름.tolist()</font>

In [70]:
arr1=np.array([10,20,30,40])
print(arr1)
### arr을 list로 바꾸는 방법!!
res=arr1.tolist()
print(res)


[10 20 30 40]
[10, 20, 30, 40]


### <font color=red>통계를 위한 연산★★★★★★★★ </font>
지금 통계하자는 건 아니다  
경영 - 마이닝  
통계 - 통계 -> 산술 추정  
컴공, AI - 예측  

--> 통계가 근간 + 컴공 모델화 + AI 예측 
--> 분석, 모델 설계 하려면 통계 비중 커지고 AI 비중 낮아짐.  
--> 신입 땐 통계 덜 중요

선형대수

range(1, 5)

In [99]:
# cf. range(1,5) -> 내장. 리스트를 준다.
for i in range(1,5):
    print(i, end="")
arr3 = np.arange(5) # array range / 초기값 안 주면 0부터 시작
arr3

1234

array([0, 1, 2, 3, 4])

**[11장: 227페이지]**

오라클로 치면 그룹함수랑 비슷
* min(), max(), sum(), avg(), count(), std(), var()
-> numpy에서는 avg 대신 min으로 쓰는 게 다르다!!

In [102]:
[arr3.sum(), arr3.mean()] # 합, 평균 (산술 연산) / 결과를 리스트로 담을 수 있다.

[10, 2.0]

**[11장: 228페이지]**

In [84]:
[arr3.std(), arr3.var()] # 표준편차, 분산 (산술 연산)

[1.4142135623730951, 2.0]

**[11장: 228페이지]**

In [85]:
[arr3.min(), arr3.max()] # 최소 최대 (산술 연산)

[0, 4]

**[11장: 228페이지]**

In [104]:
arr4 = np.arange(1,5) # range는 range인데 array로 만드는 range가 arange
arr4

array([1, 2, 3, 4])

**[11장: 228페이지]** 

In [107]:
# cf. arr.sum은 전체 array 합.

In [106]:
arr4.cumsum()  #********** 누적으로 sum. 금융쪽에서 cumsum 한다는 건 이번 한 주의 누적 수익률, 저번주부터의 누적수익률 이런 식. / 씨썸이라고 하겠다.

array([ 1,  3,  6, 10])

In [108]:
arr4.cumprod() #

array([ 1,  2,  6, 24])

#### 행렬 연산 == 선형대수

**[11장: 229페이지]**

* 행렬 ( 행, 렬 )

In [125]:
A=np.array([0,1,2,3]) # *** (4, )
A.shape ## *** (4, )

A = np.array([0, 1, 2, 3]).reshape(2,2)  # 2행, 2열
A

# array 잘 하면 numpy 잘 한다 -> 이것보다 쉬운 게 pandas

array([[0, 1],
       [2, 3]])

In [121]:
list=[[0,1,2,3],[0,1,2,3]]
arr=np.array(list)
print(list)
# 3 뽑으려면 list[0][3]
print("--"*30)
print(arr)
arr.shape
# 3 뽑으려면 arr[0][3] //// 행렬도 마찬가지로 0으로 시작!!!!!!*********주의주의주의

[[0, 1, 2, 3], [0, 1, 2, 3]]
------------------------------------------------------------
[[0 1 2 3]
 [0 1 2 3]]


(2, 4)

### <font color=red> reshape </font>

In [132]:
A= np.array([0,1,2,3])
print(A)
res=A.reshape(-1,1) # 가로를 세로로 바꾸려면 -1, 칸수는 한 칸이면 1(-1은 나머지 줄 또는 칸 수 자동 계산해준다는 의미)
print(res)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


In [142]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
print(A)
B = np.array([3, 2, 0, 1]).reshape(2,2)
print(B)

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


In [225]:
a1 = np.array([0, 10, 20, 30, 40, 50]).reshape(2,3)
print(a1)
a1 = np.array([0, 10, 20, 30, 40, 50]).reshape(-1,3)
print(a1)

[[ 0 10 20]
 [30 40 50]]
[[ 0 10 20]
 [30 40 50]]


In [140]:
A.dot(B) # 행렬 .dot : 내적(행렬곱) ***** 엄청나게 자주 쓰인다.

np.dot(A,B) # 같은 표현

array([[0, 1],
       [6, 7]])

* 전위==피봇 :: 행<->열

In [ ]:
np.transpose(A) # 전위(행과 열을 바뀐다.) (reshape는 모양을 바꾸는 거고 transpose 는 행과 열 바꿈. 엑셀에서는 pivot이라고 함.)
A.transpose()

In [ ]:
np.linalg.inv(A) # 패스

In [ ]:
np.linalg.det(A)

### 배열의 인덱싱과 슬라이싱

#### 배열의 인덱싱

리스트와 같다!

In [144]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[0], a1[4]

In [ ]:
a1[5] = 70
a1

**[11장: 231페이지]**

In [154]:
a1[[1,3,4]] # 멀티인덱스(a1에서 첫번째 값 세 번째 값 네 번째 값 뽑아라.)

array([10, 30, 40])

In [153]:
score=np.array([100,90,80,70,60])
print(score[0], score[1],score[2]) # 번째, 번째 인덱스로 가져오는 경우(약간 번거롭)
print(score[0:3])     # 슬라이싱
print(score[[1,3,4]]) # 띄엄띄엄 떼거지로 뽑을 때(리스트는 안 먹는다.)


# 대괄호 표현                     
# [] 인덱스 번째, [] 리스트(떼거지), [] 배열

100 90 80
[100  90  80]
[90 70 60]


**[11장: 232페이지]**

In [156]:
# 10 ~ 90까지 10개 씩 증가.

 ## reshape 주의 reshape(a,b) -> a*b != (배열값개수)면 에러!
a2 = np.arange(10, 110, 10).reshape(3,3)
a2

ValueError: cannot reshape array of size 10 into shape (3,3)

In [157]:
# 10 ~ 90까지 10개 씩 증가.
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [158]:
a2[0, 2]

30

In [172]:
list= [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
print(list[0][2])
#print(list[0,2]) ### list는 이런 거 없다.

30


In [169]:
arr= np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])
print(arr[0,2])
print(arr[0][2]) ## array에서도 가능. 둘 다에 가능한 문법 써라

30
30


In [174]:
a2[2, 2] = 95  # 값 바꾸기. array는 이런 표현도 된다.
print(a2)
a2[2][2] = 90
print(a2)

[[10 20 30]
 [40 50 60]
 [70 80 95]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [186]:
a2[1] ##결과는 배열(행방향) [40 50 60]

# 한 행 값 떼거지로 바꾸기 -> 어레이를 넣을 수도 있고
a2[0] = np.array([45, 55, 65])
print(a2)

# 한 행 값 떼거지로 바꾸기 -> 리스트를 통으로 넣기도 가능
            #(현업에서는 습관적으로 어레이 넣는 경우가 많다)
a2[1] = [47, 57, 67]
print(a2)

[[45 55 65]
 [47 57 67]
 [70 80 90]]
[[45 55 65]
 [47 57 67]
 [70 80 90]]


**[11장: 233페이지]**

In [189]:
a2[[0, 2], [0, 1]] ## [ ] 인덱스 안에 [] 리스트로 떼거지 불러오기
# a2[[0][2], [0][1]] 이건 안 되네..^^
# 강사님 거 가져오기.######################################################### 

array([45, 80])

**[11장: 233페이지]**

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[0]) # 0번째
res=(a[a > 3]) # 조건 a>3도 가능!! 이렇게 쓰는 게 대부분
print(res)

# a = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)
# res=(a[a > 3])
# print(res)

## 조건도 가능
 # -> array 라 가능!(값을 제어하는 애들이라)

1
[4 5 6]
[4 5 6]


**[11장: 234페이지]**

In [204]:
a = np.array([1, 4, 3, 5, 5, 8])

a[ (a % 2) == 0] # 짝수 애들만
a[ (a //3) == 1] # 3 나눴을 때 몫이 1인 애들만


a = np.array([1, 2, 3, 4, 5, 6])

#### 배열의 슬라이싱

**[11장: 234페이지]**

In [206]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [207]:
b1[:3] # 0번째부터

array([ 0, 10, 20])

In [208]:
b1[2:] # 끝까지

array([20, 30, 40, 50])

In [209]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [210]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [211]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [215]:
b2[1:3, 1:3]  # 첫번째, 두번째 행, 첫번째 두번째 열

array([[50, 60],
       [80, 90]])

In [213]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [213]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [213]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [213]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [213]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [213]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [214]:
b2[1][0:2]

array([40, 50])

In [ ]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

# Quiz

* arr [ 줄, 칸]
* arr [ [1줄,2줄] , [칸1, 칸2] ]  -> 1줄의 칸1, 2줄의 칸2
* arr [ [1줄,2줄,3줄] , [칸1, 칸2,칸3] ] -> (1줄,칸1), (2줄,칸2) (3줄,칸3)

* arr[s:e줄, s:e칸]

* -> 명확히 이해해라.


In [12]:
arr = np.array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])
print(arr)


[[10 25 35]
 [40 55 65]
 [70 80 90]]


In [241]:
print( arr [ [0,2] , 0:1 ]) # 10
                            # 70

[[10]
 [70]]


In [243]:
print( arr [ 0:2 , 0:1 ]) #10
                          # 40

[[10]
 [40]]


In [244]:
print( arr [ [0,2] ,[0,1] ])  # 10 80


[10 80]


In [7]:
# print ([ [0:2] , [0:1] ]) # --ERROR!!
# print ([ [0:2] , [0:1] ]) # --ERROR!!

print ( [ [0:1, 1:2] , 3] ) # --ERROR!!

SyntaxError: invalid syntax (Temp/ipykernel_7852/2517915316.py, line 4)

In [14]:
# 이건 왜 이렇게 나올까??  -->> 이상하다
# print( arr [ 0:2, [1,1] ])

[25 70]


In [ ]:
dataframe으로~

(4,)

#### 특별한 형태의 배열 생성

**[11장: 220페이지]**

In [ ]:
np.zeros(10)

**[11장: 220페이지]**

In [ ]:
np.zeros((3,4))

**[11장: 220 ~ 221페이지]**

In [ ]:
np.ones(5)

In [ ]:
np.ones((3,5))

**[11장: 221페이지]**

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 난수 배열의 생성

**[11장: 224 ~ 225페이지]**

In [17]:
np.random.rand(2,3)

array([[0.50327005, 0.06344113, 0.72785704],
       [0.44161959, 0.11351561, 0.8873565 ]])

In [21]:
np.random.rand()

array([0.51676984, 0.87159144])

In [16]:
np.random.rand(2,3,4) # 두 덩어리 씩, 한 덩어리에 세 줄 네 칸

array([[[0.88389428, 0.43636059, 0.16189368, 0.46506364],
        [0.0693789 , 0.88726073, 0.18449743, 0.19305122],
        [0.18425676, 0.09330828, 0.77751958, 0.27092764]],

       [[0.0158447 , 0.39169125, 0.36985499, 0.92982217],
        [0.84376109, 0.51613706, 0.44452584, 0.26286774],
        [0.35593303, 0.25740974, 0.45872957, 0.78369433]]])

**[11장: 225페이지]**

In [ ]:
np.random.randint(10, size=(3, 4)) #0부터 10개의 수(0부터 9), 3줄 4칸

In [20]:
np.random.randint(45, size=(6))+1 #로또 번호 0부터 44까지니까(45개라) +1해서 1부터 45까지

array([28,  7, 25, 34, 28, 39])

In [ ]:
np.random.randint(1, 30)